databases:
  - name: flashcards-db
    plan: free
    databaseName: flashcards
    user: flashcards

services:
  - type: web
    plan: free
    name: flashcard-manager
    runtime: python
    buildCommand: |
      pip install --upgrade pip poetry
      ./build.sh
    startCommand: poetry run gunicorn flashcard_manager.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flashcards-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: '.onrender.com'
      - key: CORS_ALLOWED_ORIGINS
        value: 'https://flashcard-manager.onrender.com,https://physical-flashcard-manager.netlify.app'
      - key: PYTHON_VERSION
        value: '3.12.7'
      - key: WEB_CONCURRENCY
        value: '4'
