# Generated by Django 5.2.6 on 2025-09-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='back',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='front',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalflashcard',
            name='back',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalflashcard',
            name='front',
            field=models.TextField(),
        ),
    ]
