# Generated by Django 5.2.6 on 2025-09-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_collection_appearance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalflashcardcollection',
            name='card_bg_color',
            field=models.CharField(blank=True, default='#f7f7f5', max_length=7),
        ),
        migrations.AddField(
            model_name='historicalflashcardcollection',
            name='card_text_color',
            field=models.CharField(blank=True, default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='historicalflashcardcollection',
            name='header_bg_color',
            field=models.CharField(blank=True, default='#e5e7eb', max_length=7),
        ),
        migrations.AddField(
            model_name='historicalflashcardcollection',
            name='header_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalflashcardcollection',
            name='header_text_color',
            field=models.CharField(blank=True, default='#111827', max_length=7),
        ),
    ]
