# Generated by Django 5.2.6 on 2025-09-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_historicalflashcardcollection_card_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcards/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='back_layout',
            field=models.CharField(choices=[('text_only', 'Text only'), ('text_left_image_right', 'Text left, image right'), ('text_right_image_left', 'Text right, image left')], default='text_only', max_length=32),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcards/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='front_layout',
            field=models.CharField(choices=[('text_only', 'Text only'), ('text_left_image_right', 'Text left, image right'), ('text_right_image_left', 'Text right, image left')], default='text_only', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalflashcard',
            name='back_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalflashcard',
            name='back_layout',
            field=models.CharField(choices=[('text_only', 'Text only'), ('text_left_image_right', 'Text left, image right'), ('text_right_image_left', 'Text right, image left')], default='text_only', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalflashcard',
            name='front_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalflashcard',
            name='front_layout',
            field=models.CharField(choices=[('text_only', 'Text only'), ('text_left_image_right', 'Text left, image right'), ('text_right_image_left', 'Text right, image left')], default='text_only', max_length=32),
        ),
    ]
