# Generated by Django 5.2.6 on 2025-09-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_flashcard_back_image_flashcard_back_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='back_extra',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='back_extra_style',
            field=models.CharField(choices=[('none', 'None'), ('tip', 'Tip'), ('warning', 'Warning'), ('check', 'Check'), ('see_also', 'See also'), ('info', 'Info')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='front_extra',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='front_extra_style',
            field=models.CharField(choices=[('none', 'None'), ('tip', 'Tip'), ('warning', 'Warning'), ('check', 'Check'), ('see_also', 'See also'), ('info', 'Info')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='historicalflashcard',
            name='back_extra',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalflashcard',
            name='back_extra_style',
            field=models.CharField(choices=[('none', 'None'), ('tip', 'Tip'), ('warning', 'Warning'), ('check', 'Check'), ('see_also', 'See also'), ('info', 'Info')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='historicalflashcard',
            name='front_extra',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalflashcard',
            name='front_extra_style',
            field=models.CharField(choices=[('none', 'None'), ('tip', 'Tip'), ('warning', 'Warning'), ('check', 'Check'), ('see_also', 'See also'), ('info', 'Info')], default='none', max_length=16),
        ),
    ]
